services:

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  rpc-server:
    build: ./rpc-server
    container_name: rpc-server
    environment:
      MONGO_URI: mongodb://mongo:27017
    # Bind directory
    volumes:
      - ../data:/data/shared
    depends_on:
      - mongo

  rest-api:
    build: ./rest-api
    container_name: rest-api
    ports:
      - "8001:8001"
    depends_on:
      - rpc-server
      - mongo

  flask-app:
    build: ./flask-app
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      REST_API_URL: http://rest-api:8001
      FLASK_SECRET_KEY: super-secret-change-me
      REQUEST_TIMEOUT: "600"
    volumes:
      - ../data:/data/shared
    depends_on:
      - rest-api
volumes:
  mongo_data:
